### PR TITLE
Fix  #147 Contact form, use post of form instead of ajax (Gold accounts)

### LINKED ISSUE #147: To prevent spam, only Gold accounts may create AJAX forms.
After configuring formspree I can't send the form, I receive 400 with the following:

{
  "error": "To prevent spam, only Gold accounts may create AJAX forms."
}

### PR DESCRIPTION
**Pull request by JPLemelin**
Update form according to doc of [formspree.io](https://formspree.io/)
Fixes #147

### CODE REVIEW

**Comment by alexislg2** [comment]
Hello. Do you plan to merge?

**Comment by ryanfox1985** [comment]
I asked for a toogle, I don't want to lose the feature.

**Comment by WaygoneWilco** [comment]
Hello, what is the status of this? Is the theme updated for using post form instead of ajax?

**Comment by GeorgeWL** [comment]
https://github.com/devcows/hugo-universal-theme/pull/152#issuecomment-403785258

**Comment by ryanfox1985** [comment]
closed by https://github.com/devcows/hugo-universal-theme/pull/203

**Pull request closed without merging**
