### PR TITLE
Social section

### PR DESCRIPTION
**Pull request by schuster-rainer**
Added the requested examples and resolved the merge conflicts @adrianmo

### CODE REVIEW

**Comment by adrianmo** [comment]
Hi @schuster-rainer, thanks again for your contributions. They are really helpful and are making this theme even better :)

Regarding this PR, I really like the way you have implemented the social information and the documentation, but I don't like the location it's showed and the appearance. The icons are too big and there is too much so much blank space between them.

s1

I think a better place for the icons would rather be below the "About Us" section, as right now it is an unused space and it's shown on every page.

s2

And instead of those big icons I'd rather use the social icons from the official Bootstrapious theme: http://universal.ondrejsvestka.cz/1-0/team-member.html

s3

I think that it'll look great with those changes. Let me know what you think :)

Thanks,
-Adrian

**Comment by schuster-rainer** [comment]
Hi @adrianmo,

sure. Will have a look at this the next couple of days in my sparetime. I've just been using the commit from @stephlocke and adding on top of that. I did just some rebasing, the documentation and the RSS linking. I'll have a look at providing an additional partial for rendering in the footer. This way you can choose.

Cheers,

**Comment by adrianmo** [comment]
Great, thanks @schuster-rainer.

**Comment by GeorgeWL** [comment]
@adrianmo @schuster-rainer 

I've a suggestion here actually.
Maybe the social icons should be as a thin strip above the footer instead, as in the same way it is done in this theme:
image

And also, personally I think the social icons provided in the original theme are garish, and the ones in the pull request are not.

**Comment by GeorgeWL** [comment]
It's possible through Hugo logic to have an Isset value in params for choosing the location isn't it?

As in, what think of something like this in the Toml: 

```
Social=enabled
#Disable or Enable for the social section.
SocialType= "default"
#Choose from "default", "bar", "front"(for only on front page), 
#"nav"(for underneath the main nav)
#Will place the social in this location based on the param set.
```

**Comment by adrianmo** [comment]
@GeorgeWL I agree with you, the original social icons look a bit garish... I don't want this port to diverge too much from the original theme, but I think the social bar you showed can be easily integrated and would be a good fit for this theme. 

Would you like to lead the effort and submit a PR? Otherwise you can just share the theme and I'll look into it when I find some time.

Thanks,
-Adrian

**Comment by GeorgeWL** [comment]
Safe to close now?

**Pull request closed without merging**
