### PR TITLE
Using the `themesDir` option instead of a softlink.

### PR DESCRIPTION
**Pull request by ringods**
Using the `themesDir` option instead of a softlink. It solves two things:
* the softlink doesn't work on Windows.
* after checkout, new contributors can immediately do `cd exampleSite` and run `hugo serve`

First PR under the #101 umbrella.

### CODE REVIEW

**Comment by ringods** [comment]
@GeorgeWL can one of you review and merge if OK?

**Comment by ringods** [comment]
@GeorgeWL can this also be merged then? ;-)

**Comment by GeorgeWL** [comment]
@ringods yeh i don't see an ssue with, so go ahead

**Comment by ringods** [comment]
@GeorgeWL I don't have the rights to merge :-)

**Comment by GeorgeWL** [comment]
ah, I'm collab, but not got merge perms, only @adrianmo and maybe @ryanfox1985 i think.

**Comment by ringods** [comment]
@adrianmo when could this be merged?

**Comment by ringods** [comment]
ping @adrianmo 

btw @GeorgeWL, did you remove the wrong label? You removed `Ready` but left `In progress`. Shouldn't it be the reverse?

**Pull request merged**
