### PR TITLE
add japanese translation

### PR DESCRIPTION
**Pull request by junichim**

### CODE REVIEW

**Comment by ryanfox1985** [comment]
hi @junichim but is not passing the tests.

**Comment by junichim** [comment]
hi @ryanfox1985 , thank you for your comment. I retry to pass the tests.

**Comment by junichim** [comment]
First, I checked my commit file and test it locally. hugo displayed japanese characteres without problems.
Next, I confirmed a Travis result page for your repo's master branch.
But there are no job log in Window. I don't get new information about why my PR doesn't pass the tests.

https://travis-ci.org/devcows/hugo-universal-theme/builds/329903644?utm_source=github_status&utm_medium=notification

Then, I enabled Travis CI for my forked repo and test whether ja.yaml file pass or not. I expected to get same error on above URL. But Travis CI passed  this file. Of course, this file is not on master branch in my forked repo (this PR is from master branch), is on other branch, called "add_lang_ja". But I guess this is not affected to Travis result because file's content is same. I confused.

https://travis-ci.org/junichim/hugo-universal-theme/builds/376436984?utm_source=github_status&utm_medium=notification

So, do I close this PR and recreate new pull request from my Travis passed branch, i.e. "add_lang_ja" ?

**Comment by poppen** [comment]
@junichim Hi, thanks for your translation. I saw your commitment, and found its `user.name` is empty. I'm sorry if I'm wrong, but it might have caused the failure of the tests. So I think it'll be passed if you fix it.

**Comment by junichim** [comment]
@poppen Thank you for your comment. I understood my mistake. This commit is before I setup configuration of user name and email. So I will close this PR and create new PR with correct user name.

**Pull request closed without merging**
