### PR TITLE
Switch from using Site.BaseURL to relative URLs.

### PR DESCRIPTION
**Pull request by vpradeep07**
When deploying a site, the site's `BaseURL` may not necessarily be known a-priori.  One real world example is when staging a site on Google app engine (the site's name is concatenated with a long random alphanumeric string).

This issue is also mentioned in the Hugo project, and a fix was merged in 2015:
gohugoio/hugo#1104

Employing this fix requires themes & layouts to use the `/foo.html` notation instead of `{{ .Site.BaseURL}}/link.html`

This PR does the following:
* Updates `exampleSite` to enable relative URLs
* Updates this theme's layouts to switch to using the `/foo.html` notation.

Once this is merged, users of the theme will have to add `RelativeURLs = true` to their `config.toml`.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
@vpradeep07 do you have a demo site in GoogleAPP Engine to see this feature?

**Comment by vpradeep07** [comment]
@ryanfox1985 - I switched from GoogleAppEngine to FirebaseHosting, but the enhancements in this PR still apply.  Here's my example site taking advantage of this feature: https://virtanatech.com/

**Comment by varnerac** [comment]
I am not sure I see the point of this. It looks to me like every change in this PR can be replaced by ```baseURL = "/"```

Have you tried that?

**Comment by vpradeep07** [comment]
@varnerac - Setting `baseurl = "/"` worked great  :+1: 
Thanks for taking a look.  Your suggestion is way cleaner that what I was trying to do.  I'll close this PR.

**Pull request closed without merging**
