### PR TITLE
Improve extensibility, add smaller features

### PR DESCRIPTION
**Pull request by timn**
Thank you for the nice port of the theme. It fits what we were looking for.

This pull request contains several minor changes, in particular aimed at improving extensiblity, re-usability of features, and styling capabilities. It also brings some new features (all are optional, the original behavior is preserved):
- ability to have awards instead of testimonials
- some shortcodes for alert boxes or centering
- Add the optional capability to show a header image or carousel for pages
- Allow to display the banner for blog posts

It would be nice to see those merged back. If you need clarification or changes please let me know.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
Hi @timn ,

thanks for the PR but right now is very difficult to make a review, it's very huge. Can you create a small PR with isolated features (1 feature for PR).

Regards.

**Comment by timn** [comment]
Hi @ryanfox1985.
It's a set of smaller feature, essentially one per commit. Splitting this up into so many PRs does not seem useful (and I'm a bit stressed on time). It's not major features that I would put as separate PR. Therefore, I'd like to ask you to look through the commits. They are in themselves rather small and as self-contained as possible. If you have questions I'm happy to answer.

**Comment by ryanfox1985** [comment]
Ok, first of all fix the tests is not passing javascript linter => https://travis-ci.org/devcows/hugo-universal-theme/builds/326154470?utm_source=github_status&utm_medium=notification

**Comment by timn** [comment]
Sorry about that. It's fixed now.

**Comment by timn** [comment]
@ryanfox1985, any chance of reviewing this anytime soon?

**Comment by timn** [comment]
@ryanfox1985, another ping. Can we proceed on this PR?

**Pull request closed without merging**
