### PR TITLE
data.features now multilingual

### PR DESCRIPTION
**Pull request by seeforschauer**
Allow make:
```
helena@skydancer:~/xxx.com> tree data                                                                                                                                               
data
├── de
│   └── features
│       ├── 1.yaml
│       ├── 2.yaml
│       ├── 3.yaml
│       ├── 4.yaml
│       ├── 5.yaml
│       └── 6.yaml
└── en
    └── features
        ├── 1.yaml
        ├── 2.yaml
        ├── 3.yaml
        ├── 4.yaml
        ├── 5.yaml
        └── 6.yaml
```

### CODE REVIEW

**Comment by ryanfox1985** [comment]
@lename do you have a demo site to see this feature?

**Comment by alexislg2** [comment]
Thank you @lename it was exactly what I was looking for. At least the features part which is the only part I tested.
Hope that will be merged soon

**Comment by Dmitry44** [comment]
Very useful functionality. Will it be merged soon?

**Comment by lename** [comment]
Hi, there are 2 things required for it. 
1) it has to be reviewed
2) it has to have a demo site. 

I have no time for 2) so I would be grateful if you do. 
For 1 I see that as the site will be ready it would become reviewed.

**Pull request closed without merging**
