### PR TITLE
Use Hugo Page Resources to load banner if not set as parameters

### PR DESCRIPTION
**Pull request by JPLemelin**
It load it with  `.Resources.GetMatch "banner*"`

You will be able to put image in the content instead of static:

```
.
└── content
    ├── blog
    │   ├── blog-post-1
    │   │   ├── index.md // That's your post content 
    │   │   └── banner.png
    │   ├── blog-post-2
    │   │   ├── index.md // That's your post content 
    │   │   └── banner-with-a-suffix.png
```

### CODE REVIEW

**Comment by ryanfox1985** [comment]
Sorry but I think that you can do the same with the markdown headers.

**Comment by salim-b** [comment]
> Sorry but I think that you can do the same with the markdown headers.

Actually I like the idea of this PR. The main advantage is that the **relationship between content file and banner image is inherently defined**: You just name the banner image `banner.*` and put it next to the content file and Hugo does the rest automatically. You don't have to define the path to the banner image in the front matter of every single content file anymore (although you still can; the `banner` key in the front matter still has precedence over this new generic approach).

Currently, you _cannot_ "do the same with the markdown headers" I think.

Additionally this PR displays the banner image at the top of each blog post: https://github.com/devcows/hugo-universal-theme/blob/8969c2e8f812fab5740bc7240d788d63e987807a/layouts/_default/single.html#L30-L36

**Comment by ryanfox1985** [comment]
I still not seeing the usage of this PR maybe with the update of the readme and config example site...
anyway override the image is something that you can do creating this file in your project: `/static/img/placeholder.png`

**Comment by salim-b** [comment]
> I still not seeing the usage of this PR maybe with the update of the readme and config example site...

Well, maybe it helps to understand if I slightly modify the file structure example:

```
.
└── content
    ├── blog
    │   ├── blog-post-1
    │   │   ├── index.md // -> content file of the first blog post
    │   │   └── banner_post1.png // -> banner image for the first blog post
    │   ├── blog-post-2
    │   │   ├── index.md // content file of the second blog post
    │   │   └── banner_post2.jpg // -> banner image for the second blog post
```

With this file structure you _don't have to define the `banner` key anymore_ in the `index.md` files!

> anyway override the image is something that you can do creating this file in your project: `/static/img/placeholder.png`

No, not really. This overrides only the _placeholder_ image which gets used if no individual image is defined for a content file. It's therefore no suitable approach if you want to have a different banner image for every content file.

**Comment by ryanfox1985** [comment]
Ok, I understood the idea, but is needed to update the [Readme](https://github.com/devcows/hugo-universal-theme/blob/master/README.md) explaining this feature.

**Comment by salim-b** [comment]
@JPLemelin Would you be willing to update this PR with an appropriate description of this feature in the README?

**Pull request closed without merging**
