### PR TITLE
add og:locale meta tag

### PR DESCRIPTION
**Pull request by salim-b**

### CODE REVIEW

**Comment by ryanfox1985** [comment]
I checked the OG tags [here => http://ogp.me/](http://ogp.me)

do you think if it has sense to add the tags [og:site_name, og:description] ??

**Comment by salim-b** [comment]
> do you think if it has sense to add the tags [og:site_name, og:description] ??

Yes, I use them myself in the site I've built based on this theme. I can make another pull request with all the remaining Open Graph (OG) tags if you like. I just added the `og:locale` tag here because it's kind of a "meta meta" tag – it describes the locale of the other OG meta tags.

**Comment by ryanfox1985** [comment]
Please, Can you add the tags [og:site_name, og:description]?

**Comment by salim-b** [comment]
> Please, Can you add the tags [og:site_name, og:description]?

I've submitted a new PR #212 with a complete overhaul of the meta tags including those two.

**Pull request closed without merging**
