### PR TITLE
Fixed favicon not updating

### PR DESCRIPTION
**Pull request by rogerssam**
Missing / prevented favicon being found and updating.

### CODE REVIEW

**Comment by modille** [comment]
Interesting... I'm guessing hugo was detecting the `rel` attribute and automatically making it relative?

An even better approach might be to use the `relUrl` and `absUrl` functions

https://gohugo.io/functions/relurl/

https://gohugo.io/functions/absurl/

**Comment by GeorgeWL** [comment]
@modille or @therog1  think you could make a pull using that instead?

feels more reliable to me to use the native functions.

**Comment by ryanfox1985** [comment]
I agree with @GeorgeWL

**Comment by therog1** [comment]
I've updated using relURL now, which fixes my issue, but there are some other paths which should perhaps also be using relURL. E.g. the two lines following (56 & 57):

```
<link href="{{ .Site.BaseURL }}css/owl.carousel.css" rel="stylesheet">
<link href="{{ .Site.BaseURL }}css/owl.theme.css" rel="stylesheet">
```

**Comment by GeorgeWL** [comment]
Working mostly with Full Stack JavaScript atm, is there not a Go or Hugo equivalent to the command `path.resolve('path','as','comma','seperated','array','forEachDir')` ?

**Comment by ryanfox1985** [comment]
@therog1 thanks for the PR, do you want to fix the other relative paths in this PR?

**Comment by therog1** [comment]
Sure, I'll fix them up when I get a few minutes.

**Comment by rogerssam** [comment]
There we go guys, I think that's fixed it for that partial...

**Pull request merged**
