### PR TITLE
Russian localization

### PR DESCRIPTION
**Pull request by Lord-Protector**

### CODE REVIEW

**Comment by adrianmo** [comment]
@Lord-Protector Thanks for the translation!

**Comment by Lord-Protector** [comment]
@adrianmo not final version, but I will update it in future.

**Comment by adrianmo** [comment]
@Lord-Protector oh sorry, I didn't see the "in-progress" label and it looked to me that it had all the translations in place. Anyway, feel free to submit another PR with more updates.

**Comment by Lord-Protector** [comment]
@adrianmo it's good that you merged, in progress, but still okay for use :)

**Comment by adrianmo** [comment]
@Lord-Protector great - thanks again for the contribution ;)

**Pull request merged**
