### PR TITLE
added Dutch translation

### PR DESCRIPTION
**Pull request by tilsammans**

### CODE REVIEW

**Comment by tilsammans** [comment]
Dutch (nl-nl) tend to leave many English terms as they are.

If you want I can provide Belgium localisation too, they usually translate more words.

**Comment by GeorgeWL** [comment]
Yeah do that too, we'd like as many languages as possible.

**Comment by tilsammans** [comment]
@GeorgeWL trouble is, it's the same language but different locale, i.e. `nl_BE`.

The files are currently named after the language only. What to do?

**Comment by GeorgeWL** [comment]
hmm dunno. two options. Replace nl_nl with nl_BE or take the time to make sure it works and try using regionals.

Cause tbh, we could do with a few other languages having iso-2-2 codes, such as en-US and en-GB. 

zh-Hans *Chinese (Simplified)*  & zh-Hant *Chinese(Traditional)* will eventually need it too when we get around to finding someone that speaks Chinese.

I feel like it should be possible to use the extended ISO without any changes as it just looks for strings that match at a cursory glance (but I've not taken the time to look properly yet.)

Either way, best to put it as separate issues & pull requests and then get this pulled @spacebabies .

**Pull request merged**
