### PR TITLE
Add option for two features per line

### PR DESCRIPTION
**Pull request by ctindel**
Right now the "Features" functionality is hard coded to put 3 features per line.  I added new functionality that still defaults to 3 features per line for backwards compatibility.  

It allows you to set a two_features_per_row configuration boolean in the Features config block.

I just realized the way I did this it has the changes from the other PR as well.  So maybe we can merge that in, and then I can update this branch so it only has the two features per line changes and merge that after.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
hello, @ctindel thanks for contribute the theme, can you attach a screenshot about your feature?

**Comment by ctindel** [comment]
@ryanfox1985 I can do that.  But any chance you could merge in my other PR for menus with sections and images first?  I screwed up my branches and that change got mixed into this PR so it would be cleaner to do that one first and then I can rebase for this one.

**Comment by ctindel** [comment]
Also @ryanfox1985 do you just want a screenshot of it in this PR or something checked into the repo?

**Comment by GeorgeWL** [comment]
> Also @ryanfox1985 do you just want a screenshot of it in this PR or something checked into the repo?

just in the PR will do, so we can see what the behaviour is like.

if you can temp host ti on a tiny bucket, that would be even better, but not a requirement.

**Comment by ryanfox1985** [comment]
closed in favour #308

**Pull request closed without merging**
