### PR TITLE
Mathjax

### PR DESCRIPTION
**Pull request by gabriel-del**
Allow to write math formulas using latex as on this [page](https://gabrieldel.netlify.com/blog/2018/07/18/eng-complementos-l1-2018.1/)

### CODE REVIEW

**Comment by GeorgeWL** [comment]
I feel like it's not universal enough to include in the skin tbh

**Comment by gabriel-del** [comment]
Thanks! How do you do interactive plots? Do you have an example?

**Comment by bmacGTPM** [comment]
> Thanks! How do you do interactive plots? Do you have an example?

It appears to be working fine now!  I'm not sure what happened, but it may have been because I upgraded the version of R I was using.  

I can't reproduce the issue, but in case it helps, here's what I was doing.  I was trying to embed a plotly figure (using RMarkdown and blogdown packages in R) into a blog post.  LaTex worked when it was a non-interactive plot, but when i switched to an interactive plot, the code $x^2$ would look something like \[x^2\].

**Comment by gabriel-del** [comment]
Great! :D

**Comment by ryanfox1985** [comment]
I think this feature is out of the scope of Universal theme. If you need external resources for your site you can include in your particular blog.

**Pull request closed without merging**
