### PR TITLE
Fix typo at contacts.html

### PR DESCRIPTION
**Pull request by josesalvador**
Fix icon class name typo at layouts/partials/contact.html

### CODE REVIEW

**Comment by ryanfox1985** [comment]
It's not a typo. The theme is using FontAwesome v5 => https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/head.html#L24

 The regular envelope class => https://fontawesome.com/icons/envelope?style=regular

**Comment by josesalvador** [comment]
> The regular envelope class => https://fontawesome.com/icons/envelope?style=regular

You're right but it does not work for me with:

- Hugo Static Site Generator v0.59.1-D5DAB232 linux/amd64 BuildDate: 2019-10-31T15:21:02Z
- Universal Theme (master branch)

The icon does not load.

**Comment by salim-b** [comment]
> It's not a typo. The theme is using FontAwesome v5

Oops, that was an over-hasty approval from my side 😬

**Comment by salim-b** [comment]
> The icon does not load.

You're sure you aren't using an ad/content blocker with some filter list rule that blocks the FA icon?

**Comment by ryanfox1985** [comment]
do you have problems with other icons? https://github.com/devcows/hugo-universal-theme/pull/234/files

**Comment by ryanfox1985** [comment]
can you generate the static site and upload to somewhere? we would be able to check it

**Comment by josesalvador** [comment]
> You're sure you aren't using an ad/content blocker with some filter list rule that blocks the FA icon?

I'll check out this afternoon again

**Comment by josesalvador** [comment]
> do you have problems with other icons? https://github.com/devcows/hugo-universal-theme/pull/234/files

No

**Comment by josesalvador** [comment]
> can you generate the static site and upload to somewhere? we would be able to check it

This afternoon I'll check it out again to ensure it's not my fault so if it's the case I'll upload the static site, of course.

Thank you.

**Comment by josesalvador** [comment]
You are both right @ryanfox1985 @salim-b 

It was my fault.

I was overwriting partials/head.html , this is the reason icon (FontAwsome v5) does not load correctly.

I'm so sorry for made you waste your time.

I'll try to do better the next time.

Thank you and congrats for your work.

Greats.

**Pull request closed without merging**
