### PR TITLE
Support for menus with sections and optional image.

### PR DESCRIPTION
**Pull request by ringods**
@GeorgeWL @adrianmo,

I reviewed the menu navigation to support more of the upstream theme. This PR offers:
* dropdown menu with single list of menu items
* dropdown menu with 4 columns of menu items, grouped in sections
* dropdown menu with 2 column wide image, followed by 2 columns of menu items grouped in sections.

Theme adapted and documentation added.

Part of #101

### CODE REVIEW

**Comment by ryanfox1985** [comment]
Looks good!

**Comment by ringods** [comment]
@GeorgeWL which dropdown issue are you talking about?

**Comment by GeorgeWL** [comment]
https://github.com/devcows/hugo-universal-theme/pull/87

**Comment by dabibbit** [comment]
Any progress on getting this merged?

**Comment by ringods** [comment]
@ryanfox1985 @adrianmo when could this be merged?

**Comment by ringods** [comment]
@ryanfox1985 @adrianmo ping.

**Comment by ctindel** [comment]
Is there any chance of getting this merged @ryanfox1985 @adrianmo looks like its been sitting for a while and it would be awesome to have this functionality!

**Comment by GeorgeWL** [comment]
@ringods fix the merge conflicts and we can merge

**Comment by ctindel** [comment]
@GeorgeWL I merged this into a new PR to remove the merge conflicts

https://github.com/devcows/hugo-universal-theme/pull/257

**Comment by ryanfox1985** [comment]
closed in favour #307

**Pull request closed without merging**
