### PR TITLE
Use position:sticky instead of javascript

### PR DESCRIPTION
**Pull request by notriddle**
This make the fixed navbar a lot less distracting, makes the page feel faster, and it's more efficient.

The big change is that it splits the top and nav bars into separate `<header>` tags, to make sure that the navbar-affixed part has the whole page as its block container. The appearance should remain the same, though.

https://caniuse.com/#feat=css-sticky

### CODE REVIEW

**Comment by GeorgeWL** [comment]
Whilst I agree here, we should probably either add in a library that recognises HTML5-only elements and then uses JavaScript to recreate the behaviour using a standard `<div>` if Browser Version doesn't support it, or we manually add a fall-back for Browsers that don't support it yet.

**Comment by notriddle** [comment]
Okay, I added a fallback (tested CSS sticky using Firefox and Edge, tested the JS fallback using IE11).

**Comment by notriddle** [comment]
@GeorgeWL @adrianmo Okay, what's keeping this from being merged?

**Comment by highergroundstudio** [comment]
I really like this and implemented in my site. Thanks!

**Comment by salim-b** [comment]
> The big change is that it splits the top and nav bars into separate `<header>` tags, to make sure that the navbar-affixed part has the whole page as its block container. The appearance should remain the same, though.

@notriddle I've just tested your changes, seems you forgot to also adapt the following files to your `<header>` tag changes:

- `layouts/404.html`
- `layouts/_default/single.html`
- `layouts/_default/list.html`
- `layouts/page/single.html`

Like in `layouts/index.html` the `<header>`/`</header>` tags have to be removed in the above files, too. Otherwise the nav/topbar won't work as expected (sticky).

**Comment by notriddle** [comment]
@salim-b @GeorgeWL Fixed them.

**Comment by notriddle** [comment]
Tip for anyone who's reviewing this: use <https://github.com/devcows/hugo-universal-theme/pull/177/files?w=1> to review the files without getting distracted by all the indentation tweaks.

**Comment by ryanfox1985** [comment]
since this is a feature not included on the original theme I would add a parameter with this option on the site configuration.

**Comment by ryanfox1985** [comment]
do you know in which browsers I can test this feature?

**Comment by ryanfox1985** [comment]
With firefox 26 that appears on red in this page: https://caniuse.com/#feat=css-sticky

The branch master works fine:

image

**Comment by notriddle** [comment]
The fallback should allow this to work in any browser that it worked in before. It's just smoother and less jumpy if you use it in a supported browser. I've tested the fallback in IE11, and tested the modern-mode with Firefox 70.

The "partial support" line are basically all WebKit and Edge, which don't support sticky position `<thead>`. Since this isn't a table element, we won't hit any of those bugs.

**Comment by GeorgeWL** [comment]
why isn't this merged yet?

it's had multiple accepted

**Comment by adrianmo** [comment]
Hi @GeorgeWL, given your involvement with the theme, I've invited you as a maintainer of the repo so that you can manage issues, pull-requests, etc. Please accept the invite as I'm sure you are the best candidate to keep this in good shape! Thanks a lot! 🚀

**Comment by ryanfox1985** [comment]
This PR is very old, I would like to test it again before merge it.

**Pull request merged**
