### PR TITLE
add correct link to author's page

### PR DESCRIPTION
**Pull request by mgisbers**
correctly link to an authors page instead to '#'.

### CODE REVIEW

**Review by ryanfox1985 — COMMENTED** [review]
Good catch, thanks for the PR.

**Comment by ryanfox1985** [comment]
@mgisbers it seems something wrong, the link it's absolute.
Example:
http://localhost:1313/authors/john-doe

Categories:
http://localhost:1313/hugo-universal-theme/categories/programming

Also the page returns not found.

**Comment by mgisbers** [comment]
Changes /authors to relURL.

**Comment by mgisbers** [comment]
There will still be an error as long as there is no content/authors/john-doe page.

**Comment by mgisbers** [comment]
With the following we could even check if an author - page exists (would like to see code improvements ;-) ):

```
{{ if isset .Params "author" }}
  {{ $authorurl := "#" }}
  {{ $authorpage := (printf "%s/%s" ("authors" | relURL) (.Params.author | urlize)) }}
  {{ with .Site.GetPage (printf "/%s/%s" ("authors") (.Params.author | urlize)) }}
    {{ $authorurl = $authorpage }}
  {{ end }}
  {{ i18n "authorBy" }} <a href="{{ $authorurl }}">{{ .Params.author }}</a>
{{ end }}

```

**Comment by ryanfox1985** [comment]
I was wondering if without author content/authors/john-doe page is possible to render at least all posts from an author.

https://moonbooth.com/hugo/authors

Only with pluralize the author in posts (now is in singular) and add the author taxanomy. What do yo think?

**Comment by mgisbers** [comment]
> I was wondering if without author content/authors/john-doe page is possible to render at least all posts from an author.
> 
> https://moonbooth.com/hugo/authors
> 
> Only with pluralize the author in posts (now is in singular) and add the author taxanomy. What do yo think?

At least the directory 'content/authors/john-doe' needs to be present to be able to iterate over the authors.
For my own page I already added 'layout/author/list.html' and 'layout/author/term.html' to render users bio/articles.

[gisbers.de](https://gisbers.de)

**Comment by ryanfox1985** [comment]
In theory steps 4/5/6 https://moonbooth.com/hugo/authors are opcional. I think only you need these steps when you want to have a author bio or you want to iterate authors.

**Comment by ryanfox1985** [comment]
perhaps the problems are:

- singular author in post, like: https://github.com/devcows/hugo-universal-theme/blame/master/exampleSite/content/blog/categories-post.md#L7
- taxanomies in config.toml

**Comment by mgisbers** [comment]
> * singular author in post, like: https://github.com/devcows/hugo-universal-theme/blame/master/exampleSite/content/blog/categories-post.md#L7

To use taxanomies we have to change from 'author:' to 'authors:' and change them to be a list instead of a string.

> * taxanomies in config.toml

Within default taxanomies 'authors' is not included, so we have to add 'tags' and 'catagories' along with 'authors'.

We could then in 'layout/authors/terms.html' iterate through taxonomie authors and list all authors with their pages. But, without having an author's page, we don't get the realname, only the the urlized version like it is stored within taxanomies.

**Comment by mgisbers** [comment]
Just found how to get the correct listing:

```
{{ range $name, $taxonomy := .Site.Taxonomies.authors }}
  <li>
    {{ with $.Site.GetPage (printf "%s/%s" "/authors" $name) }}
      {{ .Title }}
    {{ end }}
  </li>
  <ul>
    {{ range $taxonomy.Pages }}
    <li>
      <a href="{{.URL}}">{{.LinkTitle}}</a>
    </li>
    {{ end }}
  </ul>
{{end}}
</ul>
```

**Comment by mgisbers** [comment]
With PR #306 this PR is obsolete

**Comment by ryanfox1985** [comment]
closed in favour of #306

**Pull request closed without merging**
