### PR TITLE
Added travis and javascript lint.

### PR DESCRIPTION
**Pull request by ryanfox1985**

### CODE REVIEW

**Comment by adrianmo** [comment]
Thanks for the PR @ryanfox1985. Adding the JS linter is a good idea but before merging it we must make sure that it passes the tests...

**Comment by ryanfox1985** [comment]
It's very painful to fix all the files also is incompatible if someone do some improvement.

**Comment by ryanfox1985** [comment]
Done.

**Comment by adrianmo** [comment]
LGTM

**Pull request merged**
